# Generated by Django 2.0.3 on 2018-07-03 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auteur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.Auteur')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='doujinshi',
            name='serie',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='core.Serie'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doujinshi',
            name='tags',
            field=models.ManyToManyField(to='core.Tag'),
        ),
    ]
