# Generated by Django 2.0.3 on 2018-07-03 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180703_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doujinshi',
            name='serie',
        ),
        migrations.AddField(
            model_name='doujinshi',
            name='serie',
            field=models.ManyToManyField(to='core.Serie'),
        ),
    ]
