# Generated by Django 2.0.3 on 2018-07-03 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180703_2348'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoujinshiImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/doujinshi/%Y/%m/%d/')),
                ('doujinshi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Doujinshi')),
            ],
        ),
    ]
